# Generated by Django 5.2.7 on 2025-10-24 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_conversation_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sent_At',
            new_name='sent_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='userid',
            new_name='user_id',
        ),
    ]
